name: regaproject
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
# dependencies:
#   flutter:
#     sdk: flutter
    
dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.13.5
  camera: ^0.10.0+1 # ตรวจสอบให้แน่ใจว่าเวอร์ชันถูกต้อง (สามารถเปลี่ยนเป็นเวอร์ชันล่าสุดได้)
  permission_handler: ^11.4.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.1.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1  
  cloud_firestore: ^5.4.4 
  intl: ^0.17.0
  timeago: ^3.3.0
  firebase_messaging: ^15.2.1
  cloud_functions: ^5.3.1
  connectivity_plus: ^6.1.2
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.5.1
  flutter_dotenv: ^5.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
    

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/yogabg.png
    - assets/img/yoga1.png
    - assets/img/yoga2.png
    - assets/img/yoga3.png
    - assets/img/yoga4.png
    - assets/img/yoga5.png
    - assets/img/yoga_pose1.png
    - assets/img/yoga_pose2.png
    - assets/img/yoga_pose3.png
    - assets/pose_landmarker_heavy.task
    - assets/pose_landmarker_full.task
    - assets/pose_landmarker_lite.task
    - assets/img/officesyndrome.jpg
    - assets/img/butterfly.png
    - assets/img/Child.png
    - assets/img/Savasana.png
    - assets/img/Paschimottanasana.png
    - assets/img/Sukhasana.png
    - assets/img/bloodpressure.png
    - assets/img/heartdisease.png
    - assets/img/Armpain.png
    - assets/img/Backpain.png
    - assets/img/LegPain.png
    - assets/img/NeckPain.png
    - .env
    - assets/img/moutainpose.png
    - assets/img/Windrelievingpose.png
    - assets/img/BirdDog.png
    - assets/img/halfmoonpose.png
    - assets/img/SavasanawithFeetAgainstWall.png
    - assets/img/TabletoptoToePose.png
    - assets/img/UpwardSalute.png
    - assets/img/SpinalTwist.png
    - assets/img/ThreadtheNeedlePose.png
    - assets/img/SideNeckStretch.png
    - assets/img/StandingSpinalTwistPose.png
    - assets/img/bowpose.png
    - assets/img/plowpose.png
    - assets/img/LegsUptheWallPose.png
    - assets/img/halfforwardbend.png
    - assets/img/sagemarichi.png
    - assets/img/thebigtoepose.png
    - assets/img/headtokneeforwardbend.png
    - assets/img/warriorii.png
    - assets/img/easypose.png
    - assets/img/trianglepose.png
    - assets/img/dancerpose.png
    - assets/img/heropose.png
    - assets/img/extendedsideanglepose.png
    - assets/img/standingforwardbendpose.png
    - assets/img/fingersupanddownstretch.png
    - assets/img/cowfacepose.png
    - assets/img/StandingFigureFourPose.png
    - assets/img/warriori.png
    - assets/img/chairpose.png
    - assets/img/ExtendedTrianglepose.png
    - assets/img/RevolvedSideAnglePose.png
    - assets/img/chairtwistpose.png
    - assets/img/RevolvedTrianglePose.png
    - assets/img/HalfLordoftheFishespose.png
    - assets/img/TableTopwithAlternatingKneetoElbow.png
    - assets/img/halfsplitstretch.png
    - assets/img/standingbentovercalfstretch.png
    - assets/img/lungingcalfstretch.png
    - assets/img/seatedforwardfoldpose.png
    - assets/img/treepose.png
    - assets/img/StandingQuadStretchPose.png
    - assets/img/pyramidpose.png
    - assets/img/goddesspose.png
    - assets/img/camelpose.png
    - assets/img/Lowlungpose.png
    - assets/img/frogpose.png
    - assets/img/garlandpose.png
    - assets/img/butterflypose.png
    - assets/img/moutainpose.png
    - assets/img/reversewarrior.png
    - assets/img/WideLeggedForwardpose.png
    - assets/img/DownwardFacingdogpose.png
    - assets/img/cactuspose.png
    - assets/img/eaglepose.png
    - assets/img/catcow.png
    - assets/img/kneepain.png
    - assets/img/headache.png
    - assets/img/allergylung.png
    - assets/img/constipation.png
    - assets/img/everyyoga.png
    - assets/img/plantarfasciitis.png
    - assets/img/Stress.png
    - assets/img/migraine.png
    - assets/img/GERD.png
    - assets/img/Diabetes.png
    - assets/img/Afterworkout.png
    - assets/img/hippain.png
    - assets/img/shouderpain.png
    - assets/img/Beforeworkout.png
    - assets/img/assistedsidebend.png




  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
